port dom.js and lang.js from webcomponents.js
webcomponents/webcomponents-platform pull request #1
Opened 2016-12-13 21:06 UTC by notwaldorf

👀 @azakus @sorvell @kevinpschaaf

- I copied `lang.js` and `dom.js` from `webcomponents/webcomponentsjs` to here, and nuked out of date things (`Function.bind`, `window.performance.now`, `rAF`, `workingDefaultPrevented`)
- I don't know how to generate the `.travis.yml` file, but ran the 4 tests locally! 

Let me know if there's enough words in the Readme, or we need more (or less). 💪

2016-12-13 22:42 UTC, dfreedm requested changes

2016-12-13 22:42 UTC, azakus commented on README.md
> +| Polyfill   | IE10 | IE11+ | Chrome* | Firefox* | Safari 7+* | Chrome Android* | Mobile Safari* |
Remove IE 10 column

2016-12-13 22:42 UTC, azakus commented on README.md
> +| Polyfill   | IE10 | IE11+ | Chrome* | Firefox* | Safari 7+* | Chrome Android* | Mobile Safari* |
Also, Safari 9+

2016-12-13 22:42 UTC, azakus commented on LICENSE.md
> +Copyright (c) 2015 The Polymer Authors. All rights reserved.
2016

2016-12-13 22:42 UTC, azakus commented on package.json
> +    "web-component-tester": "^4.0.1"
WCT 5+ please

2016-12-13 22:46 UTC, azakus commented
Let's not bother making this PR pass tests yet.

2016-12-13 22:58 UTC, notwaldorf commented
@azakus done did changes, tests are still 😭

2016-12-14 00:25 UTC, notwaldorf commented
@azakus LOOK AT DEM GREEN TESTS

2016-12-14 00:39 UTC, dfreedm approved these changes

2016-12-14 00:39 UTC, azakus commented
👍

2016-12-14 00:39 UTC, merged