Add bower.json
webcomponents/webcomponents-platform pull request #8
Opened 2017-03-10 07:27 UTC by FluorescentHallucinogen

2017-03-27 22:24 UTC, notwaldorf requested changes

2017-03-27 22:24 UTC, notwaldorf commented on bower.json
> +    "The Polymer Project Authors (https://polymer.github.io/AUTHORS.txt)"
Just use "The Polymer Authors", please

2017-03-27 22:24 UTC, notwaldorf commented on bower.json
> +    "**/.*",
Why is this generic wildcard needed?

2017-05-12 07:49 UTC, FluorescentHallucinogen commented on bower.json
> +    "**/.*",
It's needed for excluding files like `.travis.yml`, `.gitignore`, etc. from Bower package.

2018-03-07 01:12 UTC, notwaldorf commented
Closing, this is an old PR with unaddressed requested changes.

2018-03-07 01:12 UTC, closed without merging